name: rename
description: Helps you to change or rename your flutter project BundleId and AppName for Ios, Android, MacOS and Linux platforms
version: 3.0.0
homepage: https://github.com/onatcipli/rename.git

environment:
  sdk: ">=2.12.0 <4.0.0"

executables:
  rename:

dependencies:
  args: ^2.3.0
  logger: ^2.0.2+1
  path: ^1.8.0

dev_dependencies:
  test: ^1.18.2
